from text_rendering import MONO_FONT_SIZE

BLOCK_BORDER_COLOR = (200, 200, 200)
BLOCK_BG_COLOR = (30, 32, 36)
SELECTION_BORDER_COLOR = (31, 110, 237)
RUNNING_BORDER_COLOR = (106, 171, 115)
ERROR_BORDER_COLOR = (212, 113, 106)
PENDING_NEXT_BLOCK_BORDER_COLOR = (219, 183, 53)
ARROW_COLOR = BLOCK_BORDER_COLOR

TABLE_H_PADDING = int((2/3) * MONO_FONT_SIZE)
TABLE_V_PADDING = int((1/3) * MONO_FONT_SIZE)
TABLE_BG_LIGHT = (45, 47, 51)
TABLE_BG_DARK = (26, 28, 31)

TEXTBOX_PADDING = int((2/3) * MONO_FONT_SIZE)
TEXTBOX_CARET_COLOR = BLOCK_BORDER_COLOR
TEXTBOX_BG_COLOR = TABLE_BG_LIGHT
TEXTBOX_CARET_BLINK_SPEED = 0.5
TEXTBOX_BORDER_COLOR = BLOCK_BORDER_COLOR
TEXTBOX_SELECTEC_BORDER_COLOR = SELECTION_BORDER_COLOR
TEXTBOX_MIN_HEIGHT = 150

PROPERTY_NAME_COL_WIDTH = int(7.5 * MONO_FONT_SIZE) - TABLE_H_PADDING * 2
PROPERTY_VALUE_COL_WIDTH = int(10 * MONO_FONT_SIZE) - TABLE_H_PADDING * 2
INFO_BAR_WIDTH = PROPERTY_NAME_COL_WIDTH + PROPERTY_VALUE_COL_WIDTH + TABLE_H_PADDING * 4
PROPERTY_BORDER_COLOR = BLOCK_BORDER_COLOR
PROPERTY_TEXTBOX_PADDING = 5
INFO_BAR_ARROW_SELECTOR_PADDING = 7
INFO_BAR_BG = TABLE_BG_DARK

ARROW_POINT_SELECTOR_RECT_W = 51
ARROW_POINT_SELECTOR_RECT_H = 39
ARROW_POINT_SELECTOR_RECT_COLOR = BLOCK_BORDER_COLOR
ARROW_POINT_SELECTOR_PADDING = 5
ARROW_POINT_ACTIVE_COLOR = BLOCK_BORDER_COLOR
ARROW_POINT_SELECTED_COLOR = SELECTION_BORDER_COLOR
ARROW_POINT_DISABLED_COLOR = (110, 110, 110)
