from text_rendering import FONT_SIZE

BLOCK_BORDER_COLOR = (200, 200, 200)
BLOCK_BG_COLOR = (30, 32, 36)
SELECTION_BORDER_COLOR = (31, 110, 237)
RUNNING_BORDER_COLOR = (106, 171, 115)
ERROR_BORDER_COLOR = (212, 113, 106)
ARROW_COLOR = BLOCK_BORDER_COLOR
INFO_BG_LIGHT = (45, 47, 51)
INFO_BG_DARK = (26, 28, 31)

TEXTBOX_PADDING = int((2/3) * FONT_SIZE)
TEXTBOX_CARET_COLOR = BLOCK_BORDER_COLOR
TEXTBOX_BG_COLOR = INFO_BG_LIGHT
TEXTBOX_CARET_BLINK_SPEED = 0.5
TEXTBOX_BORDER_COLOR = BLOCK_BORDER_COLOR
TEXTBOX_SELECTEC_BORDER_COLOR = SELECTION_BORDER_COLOR
TEXTBOX_MIN_HEIGHT = 150

PROPERTY_VALUE_COL_WIDTH = int(10 * FONT_SIZE)
INFO_BAR_WIDTH = int(17.5 * FONT_SIZE)
PROPERTY_H_PADDING = int((2/3) * FONT_SIZE)
PROPERTY_V_PADDING = int((1/3) * FONT_SIZE)
PROPERTY_BORDER_COLOR = BLOCK_BORDER_COLOR
PROPERTY_TEXTBOX_PADDING = 5
INFO_BAR_ARROW_SELECTOR_PADDING = 7

ARROW_POINT_SELECTOR_RECT_W = 51
ARROW_POINT_SELECTOR_RECT_H = 39
ARROW_POINT_SELECTOR_RECT_COLOR = BLOCK_BORDER_COLOR
ARROW_POINT_SELECTOR_PADDING = 5
